### ISSUE TITLE
Data Validation Breakdown

### ISSUE THREAD

**Issue by sep-he** [UBC-MDS/obesity-classifier-group17#15]
Sepehr:
Correct data file format
Correct column names
No empty observations
Missingness not beyond expected threshold

Zanan:
Correct data types in each column1
No duplicate observations
No outlier or anomalous values

Robbie:
Correct category levels (i.e., no string mismatches or single values)
Target/response variable follows expected distribution
No anomalous correlations between target/response variable and features/explanatory variables
No anomalous correlations between features/explanatory variables

**Comment by Green-zy** [comment]
the environment.yml, suggent to change pip>=24.2 to pip=24.3.1

**Comment by Green-zy** [comment]
AND do not write:
  - pip:
      - transformers
      - ucimlrepo
  because it will make the image fail to install the ucimlrepo. I spent a lot of time to fix it this afternoon. just make ucimlrepo to conda dencency. We dont need transformers. Check the latest environment.yml in github.action

**Comment by sep-he** [comment]
Seems like the data validation part is complete. 
We can merge the branch after few of the details are sorted out by Zanan.
